### ISSUE TITLE
strip question

### ISSUE THREAD

**Issue by ghost** [mjl-/gobuild#5] opened 2023-05-25 23:42 UTC
if I run this command:

~~~
go install -ldflags -s 2a.pages.dev/googleplay/cmd/googleplay@v1.1.5
~~~

the resulting tool is 4.93 MB. If I download from here:

https://beta.gobuilds.org/2a.pages.dev/googleplay

the result is 7.14 MB. are you avoiding strip for some reason?

**Comment by mjl-** [comment] 2023-05-26 07:05
I suppose the main reasons are that I'm making builds that are as "default" as possible. Go binaries being large also hasn't bothered me personally, there's always enough disk space. But I can see the appeal of stripping the binary. Currently the binaries have debugging information, but I have to admit I pretty much never need them.

I don't want to change the current default build command for the reproducible builds because then builds for code would start resulting in a different binary/hash. But adding a build mode that would strip binaries could work. We would have to add that as parameter to the transparency log. We would have to make sure not to confuse users downloading binaries. If we give them the option for a regular build and a stripped build, we'll have to explain the difference. For "just users" of binaries (instead of developers), this may confuse them.

When adding a stripped variant, we could have a look at supporting more build variations, e.g. for architecture variations, such as with GOAMD64=... etc. Or at least already ensuring there is a place to put those parameters in the transparency log.

Using UPX on binaries is also worth considering. Though I have no idea if its transformation is deterministic. And it would be somewhat annoying to set up on different platforms (likely requiring the same version on all systems to get the same binaries). Ideally we would have a upx-equivalent in Go that we could include in gobuild.

**Comment by ghost** [comment] 2023-05-26 07:40
I would avoid adding anything with UPX, but I do think stripping is a good option, either as the default or as a second download option. to offset the extra complexity of that, you could reduce the current footprint, by doing one or more of these:

- only hosting the last 10 versions
- reducing the targets to the 10 most popular
- reducing the Go versions to just the current major/minor version

**Comment by mjl-** [comment] 2023-06-22 13:29
Finally got around to it. I added only the stripped variant. We can handle future feature requests when they're made.

I don't mind the added storage space. When the gobuild server is close to running out, we can always implement removing existing build binaries from disk, and build them again when requested. One of the useful properties of reproducible builds. (: 

Thanks for the report. Let me know if there's any feedback. Otherwise, we can close this issue.

**Comment by mjl-** [comment] 2023-06-22 14:02
That had two embarrassing bugs, should be fixed now...

**Closed as completed** 2024-03-05 21:40 UTC
